services:
  db:
    image: postgres:15-alpine
    container_name: comidini-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - comidini-vol:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  comidini-vol: