/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as landingPageIndexRouteImport } from './routes/(landing-page)/index'
import { Route as authRestablecerContrasenaRouteImport } from './routes/(auth)/restablecer-contrasena'
import { Route as authRegistrarseRouteImport } from './routes/(auth)/registrarse'
import { Route as authOlvideContrasenaRouteImport } from './routes/(auth)/olvide-contrasena'
import { Route as authIniciarSesionRouteImport } from './routes/(auth)/iniciar-sesion'
import { Route as appRegistrarNegocioRouteImport } from './routes/(app)/registrar-negocio'
import { Route as appTiendasIndexRouteImport } from './routes/(app)/tiendas/index'
import { Route as appPerfilIndexRouteImport } from './routes/(app)/perfil/index'
import { Route as appTiendasShopIdRouteImport } from './routes/(app)/tiendas/$shopId'
import { Route as appPerfilEditarRouteImport } from './routes/(app)/perfil/editar'
import { Route as appTiendasMapaIndexRouteImport } from './routes/(app)/tiendas/mapa/index'

const landingPageIndexRoute = landingPageIndexRouteImport.update({
  id: '/(landing-page)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRestablecerContrasenaRoute =
  authRestablecerContrasenaRouteImport.update({
    id: '/(auth)/restablecer-contrasena',
    path: '/restablecer-contrasena',
    getParentRoute: () => rootRouteImport,
  } as any)
const authRegistrarseRoute = authRegistrarseRouteImport.update({
  id: '/(auth)/registrarse',
  path: '/registrarse',
  getParentRoute: () => rootRouteImport,
} as any)
const authOlvideContrasenaRoute = authOlvideContrasenaRouteImport.update({
  id: '/(auth)/olvide-contrasena',
  path: '/olvide-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const authIniciarSesionRoute = authIniciarSesionRouteImport.update({
  id: '/(auth)/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const appRegistrarNegocioRoute = appRegistrarNegocioRouteImport.update({
  id: '/(app)/registrar-negocio',
  path: '/registrar-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const appTiendasIndexRoute = appTiendasIndexRouteImport.update({
  id: '/(app)/tiendas/',
  path: '/tiendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPerfilIndexRoute = appPerfilIndexRouteImport.update({
  id: '/(app)/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const appTiendasShopIdRoute = appTiendasShopIdRouteImport.update({
  id: '/(app)/tiendas/$shopId',
  path: '/tiendas/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const appPerfilEditarRoute = appPerfilEditarRouteImport.update({
  id: '/(app)/perfil/editar',
  path: '/perfil/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const appTiendasMapaIndexRoute = appTiendasMapaIndexRouteImport.update({
  id: '/(app)/tiendas/mapa/',
  path: '/tiendas/mapa/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/registrar-negocio': typeof appRegistrarNegocioRoute
  '/iniciar-sesion': typeof authIniciarSesionRoute
  '/olvide-contrasena': typeof authOlvideContrasenaRoute
  '/registrarse': typeof authRegistrarseRoute
  '/restablecer-contrasena': typeof authRestablecerContrasenaRoute
  '/': typeof landingPageIndexRoute
  '/perfil/editar': typeof appPerfilEditarRoute
  '/tiendas/$shopId': typeof appTiendasShopIdRoute
  '/perfil': typeof appPerfilIndexRoute
  '/tiendas': typeof appTiendasIndexRoute
  '/tiendas/mapa': typeof appTiendasMapaIndexRoute
}
export interface FileRoutesByTo {
  '/registrar-negocio': typeof appRegistrarNegocioRoute
  '/iniciar-sesion': typeof authIniciarSesionRoute
  '/olvide-contrasena': typeof authOlvideContrasenaRoute
  '/registrarse': typeof authRegistrarseRoute
  '/restablecer-contrasena': typeof authRestablecerContrasenaRoute
  '/': typeof landingPageIndexRoute
  '/perfil/editar': typeof appPerfilEditarRoute
  '/tiendas/$shopId': typeof appTiendasShopIdRoute
  '/perfil': typeof appPerfilIndexRoute
  '/tiendas': typeof appTiendasIndexRoute
  '/tiendas/mapa': typeof appTiendasMapaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/registrar-negocio': typeof appRegistrarNegocioRoute
  '/(auth)/iniciar-sesion': typeof authIniciarSesionRoute
  '/(auth)/olvide-contrasena': typeof authOlvideContrasenaRoute
  '/(auth)/registrarse': typeof authRegistrarseRoute
  '/(auth)/restablecer-contrasena': typeof authRestablecerContrasenaRoute
  '/(landing-page)/': typeof landingPageIndexRoute
  '/(app)/perfil/editar': typeof appPerfilEditarRoute
  '/(app)/tiendas/$shopId': typeof appTiendasShopIdRoute
  '/(app)/perfil/': typeof appPerfilIndexRoute
  '/(app)/tiendas/': typeof appTiendasIndexRoute
  '/(app)/tiendas/mapa/': typeof appTiendasMapaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/registrar-negocio'
    | '/iniciar-sesion'
    | '/olvide-contrasena'
    | '/registrarse'
    | '/restablecer-contrasena'
    | '/'
    | '/perfil/editar'
    | '/tiendas/$shopId'
    | '/perfil'
    | '/tiendas'
    | '/tiendas/mapa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/registrar-negocio'
    | '/iniciar-sesion'
    | '/olvide-contrasena'
    | '/registrarse'
    | '/restablecer-contrasena'
    | '/'
    | '/perfil/editar'
    | '/tiendas/$shopId'
    | '/perfil'
    | '/tiendas'
    | '/tiendas/mapa'
  id:
    | '__root__'
    | '/(app)/registrar-negocio'
    | '/(auth)/iniciar-sesion'
    | '/(auth)/olvide-contrasena'
    | '/(auth)/registrarse'
    | '/(auth)/restablecer-contrasena'
    | '/(landing-page)/'
    | '/(app)/perfil/editar'
    | '/(app)/tiendas/$shopId'
    | '/(app)/perfil/'
    | '/(app)/tiendas/'
    | '/(app)/tiendas/mapa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRegistrarNegocioRoute: typeof appRegistrarNegocioRoute
  authIniciarSesionRoute: typeof authIniciarSesionRoute
  authOlvideContrasenaRoute: typeof authOlvideContrasenaRoute
  authRegistrarseRoute: typeof authRegistrarseRoute
  authRestablecerContrasenaRoute: typeof authRestablecerContrasenaRoute
  landingPageIndexRoute: typeof landingPageIndexRoute
  appPerfilEditarRoute: typeof appPerfilEditarRoute
  appTiendasShopIdRoute: typeof appTiendasShopIdRoute
  appPerfilIndexRoute: typeof appPerfilIndexRoute
  appTiendasIndexRoute: typeof appTiendasIndexRoute
  appTiendasMapaIndexRoute: typeof appTiendasMapaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(landing-page)/': {
      id: '/(landing-page)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/restablecer-contrasena': {
      id: '/(auth)/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof authRestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/registrarse': {
      id: '/(auth)/registrarse'
      path: '/registrarse'
      fullPath: '/registrarse'
      preLoaderRoute: typeof authRegistrarseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/olvide-contrasena': {
      id: '/(auth)/olvide-contrasena'
      path: '/olvide-contrasena'
      fullPath: '/olvide-contrasena'
      preLoaderRoute: typeof authOlvideContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/iniciar-sesion': {
      id: '/(auth)/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof authIniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/registrar-negocio': {
      id: '/(app)/registrar-negocio'
      path: '/registrar-negocio'
      fullPath: '/registrar-negocio'
      preLoaderRoute: typeof appRegistrarNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/tiendas/': {
      id: '/(app)/tiendas/'
      path: '/tiendas'
      fullPath: '/tiendas'
      preLoaderRoute: typeof appTiendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/perfil/': {
      id: '/(app)/perfil/'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof appPerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/tiendas/$shopId': {
      id: '/(app)/tiendas/$shopId'
      path: '/tiendas/$shopId'
      fullPath: '/tiendas/$shopId'
      preLoaderRoute: typeof appTiendasShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/perfil/editar': {
      id: '/(app)/perfil/editar'
      path: '/perfil/editar'
      fullPath: '/perfil/editar'
      preLoaderRoute: typeof appPerfilEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/tiendas/mapa/': {
      id: '/(app)/tiendas/mapa/'
      path: '/tiendas/mapa'
      fullPath: '/tiendas/mapa'
      preLoaderRoute: typeof appTiendasMapaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appRegistrarNegocioRoute: appRegistrarNegocioRoute,
  authIniciarSesionRoute: authIniciarSesionRoute,
  authOlvideContrasenaRoute: authOlvideContrasenaRoute,
  authRegistrarseRoute: authRegistrarseRoute,
  authRestablecerContrasenaRoute: authRestablecerContrasenaRoute,
  landingPageIndexRoute: landingPageIndexRoute,
  appPerfilEditarRoute: appPerfilEditarRoute,
  appTiendasShopIdRoute: appTiendasShopIdRoute,
  appPerfilIndexRoute: appPerfilIndexRoute,
  appTiendasIndexRoute: appTiendasIndexRoute,
  appTiendasMapaIndexRoute: appTiendasMapaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
