/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrimerosPasosIndexRouteImport } from './routes/primeros-pasos/index'
import { Route as DashboardLayoutDashboardIndexRouteImport } from './routes/_dashboard-layout/dashboard/index'
import { Route as DashboardLayoutDashboardProductosIndexRouteImport } from './routes/_dashboard-layout/dashboard/productos/index'
import { Route as DashboardLayoutDashboardPedidosIndexRouteImport } from './routes/_dashboard-layout/dashboard/pedidos/index'
import { Route as DashboardLayoutDashboardOrganizarMenuIndexRouteImport } from './routes/_dashboard-layout/dashboard/organizar-menu/index'
import { Route as DashboardLayoutDashboardHorariosIndexRouteImport } from './routes/_dashboard-layout/dashboard/horarios/index'
import { Route as DashboardLayoutDashboardConfiguracionIndexRouteImport } from './routes/_dashboard-layout/dashboard/configuracion/index'
import { Route as DashboardLayoutDashboardProductosNuevoProductoRouteImport } from './routes/_dashboard-layout/dashboard/productos/nuevo-producto'
import { Route as DashboardLayoutDashboardPedidosOrderIdRouteImport } from './routes/_dashboard-layout/dashboard/pedidos/$orderId'
import { Route as DashboardLayoutDashboardProductosEditarProductoProductIdRouteImport } from './routes/_dashboard-layout/dashboard/productos/editar-producto/$productId'

const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimerosPasosIndexRoute = PrimerosPasosIndexRouteImport.update({
  id: '/primeros-pasos/',
  path: '/primeros-pasos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardProductosIndexRoute =
  DashboardLayoutDashboardProductosIndexRouteImport.update({
    id: '/dashboard/productos/',
    path: '/dashboard/productos/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardPedidosIndexRoute =
  DashboardLayoutDashboardPedidosIndexRouteImport.update({
    id: '/dashboard/pedidos/',
    path: '/dashboard/pedidos/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardOrganizarMenuIndexRoute =
  DashboardLayoutDashboardOrganizarMenuIndexRouteImport.update({
    id: '/dashboard/organizar-menu/',
    path: '/dashboard/organizar-menu/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardHorariosIndexRoute =
  DashboardLayoutDashboardHorariosIndexRouteImport.update({
    id: '/dashboard/horarios/',
    path: '/dashboard/horarios/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardConfiguracionIndexRoute =
  DashboardLayoutDashboardConfiguracionIndexRouteImport.update({
    id: '/dashboard/configuracion/',
    path: '/dashboard/configuracion/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardProductosNuevoProductoRoute =
  DashboardLayoutDashboardProductosNuevoProductoRouteImport.update({
    id: '/dashboard/productos/nuevo-producto',
    path: '/dashboard/productos/nuevo-producto',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardPedidosOrderIdRoute =
  DashboardLayoutDashboardPedidosOrderIdRouteImport.update({
    id: '/dashboard/pedidos/$orderId',
    path: '/dashboard/pedidos/$orderId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardProductosEditarProductoProductIdRoute =
  DashboardLayoutDashboardProductosEditarProductoProductIdRouteImport.update({
    id: '/dashboard/productos/editar-producto/$productId',
    path: '/dashboard/productos/editar-producto/$productId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/primeros-pasos': typeof PrimerosPasosIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/dashboard/pedidos/$orderId': typeof DashboardLayoutDashboardPedidosOrderIdRoute
  '/dashboard/productos/nuevo-producto': typeof DashboardLayoutDashboardProductosNuevoProductoRoute
  '/dashboard/configuracion': typeof DashboardLayoutDashboardConfiguracionIndexRoute
  '/dashboard/horarios': typeof DashboardLayoutDashboardHorariosIndexRoute
  '/dashboard/organizar-menu': typeof DashboardLayoutDashboardOrganizarMenuIndexRoute
  '/dashboard/pedidos': typeof DashboardLayoutDashboardPedidosIndexRoute
  '/dashboard/productos': typeof DashboardLayoutDashboardProductosIndexRoute
  '/dashboard/productos/editar-producto/$productId': typeof DashboardLayoutDashboardProductosEditarProductoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/primeros-pasos': typeof PrimerosPasosIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/dashboard/pedidos/$orderId': typeof DashboardLayoutDashboardPedidosOrderIdRoute
  '/dashboard/productos/nuevo-producto': typeof DashboardLayoutDashboardProductosNuevoProductoRoute
  '/dashboard/configuracion': typeof DashboardLayoutDashboardConfiguracionIndexRoute
  '/dashboard/horarios': typeof DashboardLayoutDashboardHorariosIndexRoute
  '/dashboard/organizar-menu': typeof DashboardLayoutDashboardOrganizarMenuIndexRoute
  '/dashboard/pedidos': typeof DashboardLayoutDashboardPedidosIndexRoute
  '/dashboard/productos': typeof DashboardLayoutDashboardProductosIndexRoute
  '/dashboard/productos/editar-producto/$productId': typeof DashboardLayoutDashboardProductosEditarProductoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard-layout': typeof DashboardLayoutRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/primeros-pasos/': typeof PrimerosPasosIndexRoute
  '/_dashboard-layout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboard-layout/dashboard/pedidos/$orderId': typeof DashboardLayoutDashboardPedidosOrderIdRoute
  '/_dashboard-layout/dashboard/productos/nuevo-producto': typeof DashboardLayoutDashboardProductosNuevoProductoRoute
  '/_dashboard-layout/dashboard/configuracion/': typeof DashboardLayoutDashboardConfiguracionIndexRoute
  '/_dashboard-layout/dashboard/horarios/': typeof DashboardLayoutDashboardHorariosIndexRoute
  '/_dashboard-layout/dashboard/organizar-menu/': typeof DashboardLayoutDashboardOrganizarMenuIndexRoute
  '/_dashboard-layout/dashboard/pedidos/': typeof DashboardLayoutDashboardPedidosIndexRoute
  '/_dashboard-layout/dashboard/productos/': typeof DashboardLayoutDashboardProductosIndexRoute
  '/_dashboard-layout/dashboard/productos/editar-producto/$productId': typeof DashboardLayoutDashboardProductosEditarProductoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iniciar-sesion'
    | '/primeros-pasos'
    | '/dashboard'
    | '/dashboard/pedidos/$orderId'
    | '/dashboard/productos/nuevo-producto'
    | '/dashboard/configuracion'
    | '/dashboard/horarios'
    | '/dashboard/organizar-menu'
    | '/dashboard/pedidos'
    | '/dashboard/productos'
    | '/dashboard/productos/editar-producto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/primeros-pasos'
    | '/dashboard'
    | '/dashboard/pedidos/$orderId'
    | '/dashboard/productos/nuevo-producto'
    | '/dashboard/configuracion'
    | '/dashboard/horarios'
    | '/dashboard/organizar-menu'
    | '/dashboard/pedidos'
    | '/dashboard/productos'
    | '/dashboard/productos/editar-producto/$productId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard-layout'
    | '/iniciar-sesion'
    | '/primeros-pasos/'
    | '/_dashboard-layout/dashboard/'
    | '/_dashboard-layout/dashboard/pedidos/$orderId'
    | '/_dashboard-layout/dashboard/productos/nuevo-producto'
    | '/_dashboard-layout/dashboard/configuracion/'
    | '/_dashboard-layout/dashboard/horarios/'
    | '/_dashboard-layout/dashboard/organizar-menu/'
    | '/_dashboard-layout/dashboard/pedidos/'
    | '/_dashboard-layout/dashboard/productos/'
    | '/_dashboard-layout/dashboard/productos/editar-producto/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  PrimerosPasosIndexRoute: typeof PrimerosPasosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout': {
      id: '/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeros-pasos/': {
      id: '/primeros-pasos/'
      path: '/primeros-pasos'
      fullPath: '/primeros-pasos'
      preLoaderRoute: typeof PrimerosPasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout/dashboard/': {
      id: '/_dashboard-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/productos/': {
      id: '/_dashboard-layout/dashboard/productos/'
      path: '/dashboard/productos'
      fullPath: '/dashboard/productos'
      preLoaderRoute: typeof DashboardLayoutDashboardProductosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/pedidos/': {
      id: '/_dashboard-layout/dashboard/pedidos/'
      path: '/dashboard/pedidos'
      fullPath: '/dashboard/pedidos'
      preLoaderRoute: typeof DashboardLayoutDashboardPedidosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/organizar-menu/': {
      id: '/_dashboard-layout/dashboard/organizar-menu/'
      path: '/dashboard/organizar-menu'
      fullPath: '/dashboard/organizar-menu'
      preLoaderRoute: typeof DashboardLayoutDashboardOrganizarMenuIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/horarios/': {
      id: '/_dashboard-layout/dashboard/horarios/'
      path: '/dashboard/horarios'
      fullPath: '/dashboard/horarios'
      preLoaderRoute: typeof DashboardLayoutDashboardHorariosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/configuracion/': {
      id: '/_dashboard-layout/dashboard/configuracion/'
      path: '/dashboard/configuracion'
      fullPath: '/dashboard/configuracion'
      preLoaderRoute: typeof DashboardLayoutDashboardConfiguracionIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/productos/nuevo-producto': {
      id: '/_dashboard-layout/dashboard/productos/nuevo-producto'
      path: '/dashboard/productos/nuevo-producto'
      fullPath: '/dashboard/productos/nuevo-producto'
      preLoaderRoute: typeof DashboardLayoutDashboardProductosNuevoProductoRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/pedidos/$orderId': {
      id: '/_dashboard-layout/dashboard/pedidos/$orderId'
      path: '/dashboard/pedidos/$orderId'
      fullPath: '/dashboard/pedidos/$orderId'
      preLoaderRoute: typeof DashboardLayoutDashboardPedidosOrderIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/productos/editar-producto/$productId': {
      id: '/_dashboard-layout/dashboard/productos/editar-producto/$productId'
      path: '/dashboard/productos/editar-producto/$productId'
      fullPath: '/dashboard/productos/editar-producto/$productId'
      preLoaderRoute: typeof DashboardLayoutDashboardProductosEditarProductoProductIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutDashboardPedidosOrderIdRoute: typeof DashboardLayoutDashboardPedidosOrderIdRoute
  DashboardLayoutDashboardProductosNuevoProductoRoute: typeof DashboardLayoutDashboardProductosNuevoProductoRoute
  DashboardLayoutDashboardConfiguracionIndexRoute: typeof DashboardLayoutDashboardConfiguracionIndexRoute
  DashboardLayoutDashboardHorariosIndexRoute: typeof DashboardLayoutDashboardHorariosIndexRoute
  DashboardLayoutDashboardOrganizarMenuIndexRoute: typeof DashboardLayoutDashboardOrganizarMenuIndexRoute
  DashboardLayoutDashboardPedidosIndexRoute: typeof DashboardLayoutDashboardPedidosIndexRoute
  DashboardLayoutDashboardProductosIndexRoute: typeof DashboardLayoutDashboardProductosIndexRoute
  DashboardLayoutDashboardProductosEditarProductoProductIdRoute: typeof DashboardLayoutDashboardProductosEditarProductoProductIdRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutDashboardPedidosOrderIdRoute:
    DashboardLayoutDashboardPedidosOrderIdRoute,
  DashboardLayoutDashboardProductosNuevoProductoRoute:
    DashboardLayoutDashboardProductosNuevoProductoRoute,
  DashboardLayoutDashboardConfiguracionIndexRoute:
    DashboardLayoutDashboardConfiguracionIndexRoute,
  DashboardLayoutDashboardHorariosIndexRoute:
    DashboardLayoutDashboardHorariosIndexRoute,
  DashboardLayoutDashboardOrganizarMenuIndexRoute:
    DashboardLayoutDashboardOrganizarMenuIndexRoute,
  DashboardLayoutDashboardPedidosIndexRoute:
    DashboardLayoutDashboardPedidosIndexRoute,
  DashboardLayoutDashboardProductosIndexRoute:
    DashboardLayoutDashboardProductosIndexRoute,
  DashboardLayoutDashboardProductosEditarProductoProductIdRoute:
    DashboardLayoutDashboardProductosEditarProductoProductIdRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  PrimerosPasosIndexRoute: PrimerosPasosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
