/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrimerosPasosIndexRouteImport } from './routes/primeros-pasos/index'
import { Route as DashboardLayoutDashboardIndexRouteImport } from './routes/_dashboard-layout/dashboard/index'
import { Route as DashboardLayoutDashboardHorariosIndexRouteImport } from './routes/_dashboard-layout/dashboard/horarios/index'
import { Route as DashboardLayoutDashboardConfiguracionIndexRouteImport } from './routes/_dashboard-layout/dashboard/configuracion/index'

const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimerosPasosIndexRoute = PrimerosPasosIndexRouteImport.update({
  id: '/primeros-pasos/',
  path: '/primeros-pasos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardHorariosIndexRoute =
  DashboardLayoutDashboardHorariosIndexRouteImport.update({
    id: '/dashboard/horarios/',
    path: '/dashboard/horarios/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardConfiguracionIndexRoute =
  DashboardLayoutDashboardConfiguracionIndexRouteImport.update({
    id: '/dashboard/configuracion/',
    path: '/dashboard/configuracion/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/primeros-pasos': typeof PrimerosPasosIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/dashboard/configuracion': typeof DashboardLayoutDashboardConfiguracionIndexRoute
  '/dashboard/horarios': typeof DashboardLayoutDashboardHorariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/primeros-pasos': typeof PrimerosPasosIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/dashboard/configuracion': typeof DashboardLayoutDashboardConfiguracionIndexRoute
  '/dashboard/horarios': typeof DashboardLayoutDashboardHorariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard-layout': typeof DashboardLayoutRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/primeros-pasos/': typeof PrimerosPasosIndexRoute
  '/_dashboard-layout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboard-layout/dashboard/configuracion/': typeof DashboardLayoutDashboardConfiguracionIndexRoute
  '/_dashboard-layout/dashboard/horarios/': typeof DashboardLayoutDashboardHorariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iniciar-sesion'
    | '/primeros-pasos'
    | '/dashboard'
    | '/dashboard/configuracion'
    | '/dashboard/horarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/primeros-pasos'
    | '/dashboard'
    | '/dashboard/configuracion'
    | '/dashboard/horarios'
  id:
    | '__root__'
    | '/'
    | '/_dashboard-layout'
    | '/iniciar-sesion'
    | '/primeros-pasos/'
    | '/_dashboard-layout/dashboard/'
    | '/_dashboard-layout/dashboard/configuracion/'
    | '/_dashboard-layout/dashboard/horarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  PrimerosPasosIndexRoute: typeof PrimerosPasosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout': {
      id: '/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeros-pasos/': {
      id: '/primeros-pasos/'
      path: '/primeros-pasos'
      fullPath: '/primeros-pasos'
      preLoaderRoute: typeof PrimerosPasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard-layout/dashboard/': {
      id: '/_dashboard-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/horarios/': {
      id: '/_dashboard-layout/dashboard/horarios/'
      path: '/dashboard/horarios'
      fullPath: '/dashboard/horarios'
      preLoaderRoute: typeof DashboardLayoutDashboardHorariosIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard-layout/dashboard/configuracion/': {
      id: '/_dashboard-layout/dashboard/configuracion/'
      path: '/dashboard/configuracion'
      fullPath: '/dashboard/configuracion'
      preLoaderRoute: typeof DashboardLayoutDashboardConfiguracionIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutDashboardConfiguracionIndexRoute: typeof DashboardLayoutDashboardConfiguracionIndexRoute
  DashboardLayoutDashboardHorariosIndexRoute: typeof DashboardLayoutDashboardHorariosIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutDashboardConfiguracionIndexRoute:
    DashboardLayoutDashboardConfiguracionIndexRoute,
  DashboardLayoutDashboardHorariosIndexRoute:
    DashboardLayoutDashboardHorariosIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  PrimerosPasosIndexRoute: PrimerosPasosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
